name: Terraform Static Analysis
on: [push, pull_request]
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/tf-app
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check -recursive
      - run: terraform validate
      # Optionally add TFLint later
